services:
  db:
    container_name: postgres
    image: postgres:14.1
    environment:
      POSTGRES_USER: chetan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
    #---------------------------
  customer-api:
    container_name: customer-api
    image: malapatichetan/customer-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
      SPRING_DATASOURCE_USERNAME: chetan
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    #---------------------------
networks:
  db:
    driver: bridge
volumes:
  db: